 const ActionTypes = {

    ERROR : "ERROR",
    RADIOERROR : "RADIOERROR",
    CURRENTCOMPANYJOBS: 'CURRENTCOMPANYJOBS',
    ALLCOMPANYJOBS:'ALLCOMPANYJOBS',
    CURRENTSTUDENT:'CURRENTSTUDENT'
}

export default ActionTypes;
