 const ActionTypes = {

    ERROR : "ERROR",
    RADIOERROR : "RADIOERROR",
    CURRENTCOMPANYJOBS: 'CURRENTCOMPANYJOBS',
    ALLCOMPANYJOBS:'ALLCOMPANYJOBS',
    CURRENTSTUDENT:'CURRENTSTUDENT',
    APPLIEDJOBS:'APPLIEDJOBS',
    ALLSTUDENTS:'ALLSTUDENTS',
    RADIOERROR:'RADIOERROR'
}

export default ActionTypes;
